# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nickai < Formula
  desc "Conversational trading terminal for autonomous finance"
  homepage "https://github.com/frankybeatz/nickai-cli"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/frankybeatz/nickai-cli/releases/download/v0.7.0/nickai-darwin-amd64.tar.gz"
      sha256 "fcf839ddbe21682a2e9f52a7cccca540a0039c0cd54a53459b772279edb4dd22"

      define_method(:install) do
        bin.install "nickai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/frankybeatz/nickai-cli/releases/download/v0.7.0/nickai-darwin-arm64.tar.gz"
      sha256 "1065ccd05cf884de617c23367101641408af915eda77982a34a0b404ef89f38c"

      define_method(:install) do
        bin.install "nickai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/frankybeatz/nickai-cli/releases/download/v0.7.0/nickai-linux-amd64.tar.gz"
      sha256 "ab70d0f544242b9c13b60128bb396ee9b6f247976f04948e160fe074a1940a65"
      define_method(:install) do
        bin.install "nickai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/frankybeatz/nickai-cli/releases/download/v0.7.0/nickai-linux-arm64.tar.gz"
      sha256 "7483acf7fc3075151895d799cd49b773cca96067cb1429a0dbfc97cb50918ee9"
      define_method(:install) do
        bin.install "nickai"
      end
    end
  end

  test do
    system "#{bin}/nickai", "--version"
  end
end
