# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NickaiCli < Formula
  desc "Conversational trading terminal for autonomous finance"
  homepage "https://github.com/frankybeatz/nickai-cli"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/frankybeatz/nickai-cli/releases/download/v0.4.0/nickai-darwin-amd64.tar.gz"
      sha256 "4e38f6c8892f2b0d6d7ec2c08d84bff6c4da0e075bf7c7d2d4e7f9acb7c6ccff"

      define_method(:install) do
        bin.install "nickai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/frankybeatz/nickai-cli/releases/download/v0.4.0/nickai-darwin-arm64.tar.gz"
      sha256 "de47b250709ee724bf5c32677c5d7976564e4252db7a408610e73beb7df619f1"

      define_method(:install) do
        bin.install "nickai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/frankybeatz/nickai-cli/releases/download/v0.4.0/nickai-linux-amd64.tar.gz"
      sha256 "9b2f3569eebc69213813af4359da438bbbd3801d859afee21dfbe69cecb0876c"
      define_method(:install) do
        bin.install "nickai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/frankybeatz/nickai-cli/releases/download/v0.4.0/nickai-linux-arm64.tar.gz"
      sha256 "29653054ce0856cfad9043344d787487170032d2cee2c2f93edd9504ceea68ea"
      define_method(:install) do
        bin.install "nickai"
      end
    end
  end

  test do
    system "#{bin}/nickai", "--version"
  end
end
