# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NickaiCli < Formula
  desc "Conversational trading terminal for autonomous finance"
  homepage "https://github.com/frankybeatz/nickai-cli"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/frankybeatz/nickai-cli/releases/download/v0.5.0/nickai-darwin-amd64.tar.gz"
      sha256 "bd0ffffd71d163713477b08274365e45f43703a1547d89984a8ccc02c2dde826"

      define_method(:install) do
        bin.install "nickai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/frankybeatz/nickai-cli/releases/download/v0.5.0/nickai-darwin-arm64.tar.gz"
      sha256 "0184952deac97616e6c90f5fe0031ca6ca0549bdbf70ba5981b820bd88a5fa1c"

      define_method(:install) do
        bin.install "nickai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/frankybeatz/nickai-cli/releases/download/v0.5.0/nickai-linux-amd64.tar.gz"
      sha256 "9b22cf961c9d0545adc1997a8d402efb3b7cbc57679bc129426823d96e8da3aa"
      define_method(:install) do
        bin.install "nickai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/frankybeatz/nickai-cli/releases/download/v0.5.0/nickai-linux-arm64.tar.gz"
      sha256 "b297e3a03ff57d331d70f9cf5ec56de34cc356964339833d65d333de4ff22c6e"
      define_method(:install) do
        bin.install "nickai"
      end
    end
  end

  test do
    system "#{bin}/nickai", "--version"
  end
end
